<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<title>Admin Dashboard</title>
</head>
<body>
<center><b><font size ="20">Admin Dashboard</font></b></center>
<br>							  
<br>
	Customer Representative:
	<button onclick="window.location.href='changeCustomerRep.jsp?type=add'">Add</button>
	<button onclick="window.location.href='changeCustomerRep.jsp?type=edit'">Edit</button>
	<button onclick="window.location.href='changeCustomerRep.jsp?type=delete'">Delete</button>
	
	<br>
	<br>
	
	Customer:
	<button onclick="window.location.href='changeCustomer.jsp?type=add'">Add</button>
	<button onclick="window.location.href='changeCustomer.jsp?type=edit'">Edit</button>
	<button onclick="window.location.href='changeCustomer.jsp?type=delete'">Delete</button>
	
	<br>
	<br>

	<form method= "post" action="salesReport.jsp">
		<input type="submit" value="Generate Sales Report">
	</form>
	<br>
	<form method= "post" action="reservations.jsp">
		<input type="submit" value="View all Reservations">
	</form>
	
	<br>
	
	Produce a Summary of Revenue Generated By:
	<button onclick="window.location.href='revenueReport.jsp?type=flight'">Flight</button>
	<button onclick="window.location.href='revenueReport.jsp?type=airline'">Airline</button>
	<button onclick="window.location.href='revenueReport.jsp?type=customer'">Customer</button>
	<br>
	<br>
	<form method= "post" action="flights.jsp">
		<input type="submit" value="List all Flights by Airport">
	</form>
	<br>
	<form method= "post" action="customerHighestRevenue.jsp">
		<input type="submit" value="Customer Who Generated Most Total Revenue">
	</form>
	<br>
	<form method= "post" action="mostActiveFlights.jsp">
		<input type="submit" value="Most Active Flights">
	</form>
	

</body>
</html>